version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/packages/node"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "nuget"
    directory: "/packages/dotnet"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gomod"
    directory: "/packages/go"
    schedule:
      interval: "weekly"
      day: "sunday"